### ISSUE TITLE
Bug Export ODT

### ISSUE THREAD

**Issue by fire2418** [TECLIB/mreporting#1]
Bonjour, 

Tout d'abord félicitations pour ce plugin, qui m'est très utile au quotidien.

Je test actuellement la RC de la version 2.3 de mreporting, pour GLPI en version 0.84.7 (prod) et 0.84.8 (test)

J'ai rencontré un bug, que ce soit en RC1 ou RC2, quelque soit le modèle utilisé (writer.odt, word.odt, withoutdata.odt).

Lors de l'explort d'un ou plusieurs rapports, via le bouton "Exporter:ODT", quelquesoit la durée, j'ai les messages suivants:

PHP Notice: Undefined index: delay in /var/www/glpi/plugins/mreporting/inc/helpdesk.class.php at line 43
PHP Notice: Undefined index: randname in /var/www/glpi/plugins/mreporting/inc/helpdesk.class.php at line 44

Fatal error: Call to a member function fetch_assoc() on a non-object in /var/www/glpi/inc/dbmysql.class.php on line 298

Avez-vous connaissance de ce bug?
Merci par avance pour votre retour.

**Comment by fire2418** [comment]
Complément d'information:

Le problème persiste, même dans la dernière version de mreporting. Ci-après l'erreur.
![erreur_mreporting](https://cloud.githubusercontent.com/assets/10270520/6779325/2c414760-d15b-11e4-8032-bfc565f34708.PNG)

**Comment by orthagh** [comment]
Vous avez des erreurs assez grossières qui ne devraient pas apparaître.
Avez-vous essayé de réinstaller complètement les plugin depuis le menu configuration > Plugins.
C'est à dire le désinstaller puis le réinstaller.

Ensuite si le bug d'export persiste, pouvez vous m'indiquer à quel endroit de l'interface (il y a plusieurs export existant), l'erreur se produit ?

Merci d'avance.

**Comment by fire2418** [comment]
Bonjour, 

Merci pour votre retour.

L'extension est désinstallée puis réinstallée à chaque mise à jour, à chaque fois j'effectue le petit nettoyage depuis le menu plugin avant de procéder à la réinstallation. Le bug se produit sur chacun des exports. Sur le Reporting Helpdesk Avancé, j'ai la même erreur, mais avec des informations en plus sur
![erreur_helpdeskplus](https://cloud.githubusercontent.com/assets/10270520/6802409/786415ca-d230-11e4-81a0-e63afdcc312e.PNG)

J'ai testé avec et sans données (bien entendu en sélectionnant les modèles correspondants dans les préférences du plugin). Par contre, je me posais une question: pourriez-vous me confirmer qu'il n'y a pas besoin de composants libreoffice / openoffice sur le serveur pour que cela fonctionne ?

Si vous souhaitez plus d'informations sur le soucis, je suis à votre disposition, merci encore une fois pour votre réponse :)

**Comment by orthagh** [comment]
Ca doit être mieux avec les deux dernier commits.
Pouvez vous essayer avec l'archive du repo avant que je ne fasse une réelle release :   

0.84 -> branche master
0.85 -> branche 0.85/work

Merci d'avance

**Comment by orthagh** [comment]
J'ai poussé mes commits sur la forge privée de Teclib ce matin au moment de ma réponse à cette issue.

C'est maintenant public.

**Comment by fire2418** [comment]
Je ne vois pas de commit depuis deux jours. 
![repo_mreporting](https://cloud.githubusercontent.com/assets/10270520/6822330/2851322a-d2df-11e4-87ce-38daedd69b79.PNG)

J'ai au cas ou testé avec le master actuel, en désinstallant l'extension puis en la réinstallant, ça n'a rien changé.
Le pastebin dbmysql.class.php: http://pastebin.com/HUwu1rb1
Le pastebin php-error.log: http://pastebin.com/mFArcpae

**Comment by fire2418** [comment]
Avec la nouvelle version ça fonctionne parfaitement en version 0.84. Je teste en 0.85.2 
Merci beaucoup ! :)
