### ISSUE TITLE
Erreur SQL lors de la migration depuis une ancienne version du plugin

### ISSUE THREAD

**Issue by neeftarah** [TECLIB/mreporting#3]
La nouvelle version de mreporting intégrant le Dashboard vérifie dans le setup (L 78) si l'utilisateur dispose d'une configuration personnelle.
Hors, lors d'une migration, le plugin reste activer et le code est donc executé, mais la table de base de données de la configuration du dashboard n'est pas installée (pas avant la mise à jour).

**Comment by orthagh** [comment]
fix by a5a54cbbb667ab65a327cedcb0ee4d44fc7d5d4f

To watch !
