### ISSUE TITLE
New reports are not available

### ISSUE THREAD

**Issue by yannick-photobox** [TECLIB/mreporting#6]
Hi,

I have created a new file in /var/www/glpi/plugins/mreporting/inc/ to make my own reports. It is working well.
Every time I add a new function to this file, to create a new report, I have to uninstall and re-install the plugin. Otherwise the table glpi_plugin_mreporting_configs is not updated and  the report is not available.
Is there a way to reload this table without un-installing the plugin? (disable/enable is not enough)

Kind regards,

GLPI 0.85.2
MREPORTING 0.85-1.0RC4

**Comment by orthagh** [comment]
Hi, 

Go into config (the wrench icon) and click on "Initialize graphics configuration" to detect new reports.

Regards.

**Comment by yannick-photobox** [comment]
I knew there was a trick.
Thank you very much, very helpful as usual.
